name: sensoryscope
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^3.0.0
  vibration: ^1.7.3
  percent_indicator: ^2.1.1+1
  shared_preferences: ^0.5.6
  flutter_staggered_grid_view: ^0.3.0
  flutter_bloc: ^4.0.0
  random_string: ^2.0.1
  neumorphic: ^0.4.0
  equatable: ^1.2.0
  image_picker: ^0.6.7+2
  easy_localization: ^2.3.2
  flutter_tagging: ^1.1.0
  cached_network_image: ^2.0.0
  cached_video_player: 1.0.3
  curved_navigation_bar: ^0.3.3
  introduction_screen: ^1.0.7
  liquid_swipe: ^1.5.0
  bloc: ^4.0.0
  meta: ^1.1.6
  getwidget: 1.1.3
  path_provider: ^1.6.5
  image_gallery_saver: ^1.2.2
  permission_handler: ^4.2.0+hotfix.3
  dio: ^3.0.9
  painter: ^0.4.0
  sqflite: ^1.0.0
  flutter_launcher_icons: ^0.7.0
  flutter_fluid_slider: ^0.0.1
  wave: ^0.0.8
  flutter_login:
  path: ^1.6.4
  responsive_framework: ^0.0.8
  rflutter_alert: ^1.0.3
  flutter_svg: ^0.18.1
  spincircle_bottom_bar: ^1.0.0
  page_transition: ^1.1.5
  flare_flutter: ^2.0.3
  duration: ^2.0.11
  rect_getter: ^0.1.0
  flutter_neumorphic: ^3.0.0
  rxdart: ^0.24.1
    # for local file test
  assets_audio_player: ^2.0.10
  http: ^0.12.1
  provider: ^4.1.2
  file: ^5.0.4
  flutter_audio_recorder: 0.5.5
  flutter_audio_query: ^0.3.4+1
  flutter_xlider: ^3.4.0
  font_awesome_flutter: ^8.8.1
  adobe_xd: ^1.0.0+1
  build_web_compilers: '>=1.0.0 <2.0.0'
#  music_player: ^0.1.5
  audioplayers: ^0.16.1
#  audioplayer: 0.8.1
#  audioplayer_web: 0.7.1
#  fileaudioplayer: ^1.0.0
  audio_manager: ^0.5.3
  music_player: ^0.1.5
  fluttertoast: ^7.1.5
  toast: ^0.1.5
  flutter_staggered_animations: ^0.1.2
  shimmer: ^1.1.2
  dynamic_color_theme: ^1.1.1
  flutter_material_color_picker:
  screen: ^0.0.4
  highlighter_coachmark: ^0.0.3
  flutter_slidable: ^0.4.9





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/languages/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
